import Head from 'next/head';
import React from 'react';

export const Header: React.FC = () => <Head>
	<title>Panagiotis Gkavogiannis' Portfolio</title>
	<meta name="description" content="Generated by create next app"/>
	<link rel="icon" href="/assets/favicon.ico"/>
</Head>;